DROP DATABASE IF EXISTS aw305buup4rcyadi;

CREATE DATABASE aw305buup4rcyadi;

USE aw305buup4rcyadi;

CREATE TABLE burgers (
	id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    burger_name VARCHAR(50) NOT NULL,
    devoured BOOL NOT NULL DEFAULT 0
);